FROM node:19.3

WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY yarn.lock .

RUN apt-get update && apt-get install -y ffmpeg

RUN npm install -g typescript
RUN npm install -g ts-node
#USER node

COPY . .

RUN yarn install

#RUN sudo chown -R node:node ./app

EXPOSE 4005

CMD ["yarn", "run", "dev"]
