node:19.3.0-alpine

WORKDIR /usr

COPY package.json .
COPY tsconfig.json .
COPY yarn.lock .

COPY src ./src

RUN npm install -g yarn
RUN yarn install
RUN yarn run build

EXPOSE 4005

## this is stage two, where the app actually runs
FROM node:19.3.0-alpine

WORKDIR /usr

COPY package.json .
COPY tsconfig.json .
COPY yarn.lock .

RUN yarn  install --only=production
COPY --from=0 /usr/dist .
RUN yarn add pm2 -g
EXPOSE 80
CMD ["pm2-runtime","app.js"]
